repository: bpasanek/puzzlepoesis # needed to run locally (see default.html)

l#theme: jekyll-theme-minimal

collections:
    - puzzlepoems
    - people

baseurl: /puzzlepoesis

#sass:
 #   sass_dir: _sass

scss:
    scss_dir: _scss

collections:
    puzzlepoems:
        output: true
    people:
        output: true
    category:
        output: true
        #permalink: /:puzzlepoems/:name/

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"