#theme: jekyll-theme-minimal

collections:
    - puzzlepoems
    - people

baseurl: /puzzlepoesis

collections:
    puzzlepoems:
        output: true
    people:
        output: true
        #permalink: /:puzzlepoems/:name/